version: '3.8'
services:
  php:
    image: yiisoftware/yii2-php:8.3-fpm
    volumes:
      - ./:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/app
    depends_on:
      - php

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
